spring:
  jpa:
    showSql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddlAuto: create
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#logging:
#  level:
#    root: DEBUG